version: "3.1"


services:

  basephp:
    build: basephp
    image: everymedia_basephp
    container_name: everymedia-basephp
    volumes:
      - ..:/var/www/everymedia
      - ${VOLUMES_DIR}/logs/phpconfig:/var/log


  redis:
    image: redis:6.0-alpine


  db:
    image: mysql:8.0
    restart: unless-stopped
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=everymedia
      - MYSQL_USER=everymedia
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PW}
      - MYSQL_PASSWORD=${MYSQL_PW}

    ports:
      - "13306:3306"
    volumes:
      - ${VOLUMES_DIR}/mysql/lib:/var/lib/mysql
      - ${VOLUMES_DIR}/mysql/conf:/etc/mysql/conf.d
      - ${VOLUMES_DIR}/logs/mysql/logs:/var/log/mysql


  nginx:
    image: nginx:1.19-alpine
    restart: unless-stopped
    container_name: everymedia-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ..:/var/www/everymedia
      - ${VOLUMES_DIR}/logs/nginx:/var/log/nginx
    ports:
      - "8000:8000"
    links:
      - php-fpm


  php-fpm:
    build: php-fpm
    restart: unless-stopped
    container_name: everymedia-php-fpm
    volumes:
      - ./php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
      - ..:/var/www/everymedia
      - ${VOLUMES_DIR}/laravel_storage:/var/www/everymedia/storage
      - ${VOLUMES_DIR}/logs/php-fpm:/var/log/php-fpm
    links:
      - db
      - redis
    depends_on:
      - redis
      - db
      - basephp


  queue:
    build: queue
    restart: unless-stopped
    volumes:
      - ..:/var/www/everymedia
      - ${VOLUMES_DIR}/laravel_storage:/var/www/everymedia/storage
    links:
      - db
      - redis
    depends_on:
      - redis
      - db
      - basephp
      - php-fpm


# not the bast way to run composer/migrations but it allows us to start the project with a single `docker-compose up`

  composer:
    build: composer
    restart: "no"
    volumes:
      - ..:/var/www/everymedia
    depends_on:
      - redis
      - db
      - basephp
      - php-fpm

  cron:
    build: ./cron
    restart: unless-stopped
    volumes:
      - ..:/var/www/everymedia
      - ${VOLUMES_DIR}/laravel_storage:/var/www/everymedia/storage
    links:
      - db
      - redis
    depends_on:
      - redis
      - db
      - basephp
      - php-fpm


  db-migrations-seeder:
    build: db-migrations-seeder
    restart: "no"
    volumes:
      - ..:/var/www/everymedia
    links:
      - db
    depends_on:
      - db
      - basephp
